export interface IThemeType {
  COLOR_MAIN: string;
  COLOR_MAIN_HOVER: string;

  BACKGROUND: string;
  BACKGROUND_NAVIGATION: string;
  BACKGROUND_EXIT: string;
  BACKGROUND_EXIT_HOVER: string;
  BACKGROUND_MINIMISE: string;
  BACKGROUND_MINIMISE_HOVER: string;
  BACKGROUND_MAXIMISE: string;
  BACKGROUND_MAXIMISE_HOVER: string;
  BACKGROUND_BUTTON: string;
  BACKGROUND_MENU_ITEM_HOVER: string;
  BACKGROUND_MESSAGES: string;

  BORDER: string;
  BORDER_NAVIGATION: string;
  BORDER_BUTTON: string;
  BORDER_BUTTON_HOVER: string;

  TEXT_PRIMARY: string;
  TEXT_SECONDARY: string;

  ICON_PRIMARY: string;
  ICON_SECONDARY: string;

  TRANSITION_TIME: string;
  TRANSITION_TIME_SHORT: string;
  TRANSITION_EASE: string;
}

export const theme: IThemeType = {
  COLOR_MAIN: 'hsl(218, 98%, 51%)',
  COLOR_MAIN_HOVER: 'hsl(210,91%,34%)',

  BACKGROUND: 'hsl(0,0%,100%)',
  BACKGROUND_NAVIGATION: 'hsla(214, 24%, 11%, 0.75)',
  BACKGROUND_EXIT: 'hsl(1, 100%, 68%)',
  BACKGROUND_EXIT_HOVER: 'hsl(1, 56%, 52%)',
  BACKGROUND_MINIMISE: 'hsl(39, 100%, 63%)',
  BACKGROUND_MINIMISE_HOVER: 'hsl(39, 80%, 52%)',
  BACKGROUND_MAXIMISE: 'hsl(143, 100%, 40%)',
  BACKGROUND_MAXIMISE_HOVER: 'hsl(143, 84%, 37%)',
  BACKGROUND_BUTTON: 'hsl(217,33%,17%)',
  BACKGROUND_MENU_ITEM_HOVER: 'hsla(221,69%,91%,0.1)',
  BACKGROUND_MESSAGES: 'hsla(0, 0%, 0%, 0.25)',

  BORDER: 'hsl(223,29%,26%)',
  BORDER_NAVIGATION: 'hsla(224, 25%, 18%, 0.75)',
  BORDER_BUTTON: 'hsl(219,25%,21%)',
  BORDER_BUTTON_HOVER: 'hsl(219,26%,26%)',

  TEXT_PRIMARY: 'hsl(0,0%,100%)',
  TEXT_SECONDARY: 'hsl(0,0%,64%)',

  ICON_PRIMARY: 'hsl(0,0%,100%)',
  ICON_SECONDARY: 'hsl(0,0%,64%)',

  TRANSITION_TIME: '0.8s',
  TRANSITION_TIME_SHORT: '0.5s',
  TRANSITION_EASE: 'ease-in-out',
};
